# This blueprint deploys n8n workflow automation tool with a PostgreSQL database

services:
  # n8n Web Service
  - type: web
    runtime: image
    name: n8n-app
    image:
      url: n8nio/n8n:latest
    region: frankfurt
    plan: free
    autoDeploy: true
    
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-database
          property: database
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-database
          property: host
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-database
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-database
          property: password
      - key: GENERIC_TIMEZONE
        value: UTC
      - key: N8N_ENCRYPTION_KEY
        value: sD7lFhIIeS
      
      # n8n Configuration
      - key: N8N_HOST
        value: n8n.onrender.com

      - key: TZ
        value: UTC
        
      - key: WEBHOOK_URL
        value: https://your-n8n-app.onrender.com  # Update with your actual domain
      
      
      # Log level
      - key: N8N_LOG_LEVEL
        value: info

      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"

# PostgreSQL Database
databases:
  - name: n8n-database
    databaseName: n8n_db
    user: n8n_user
    plan: free
    region: frankfurt
    
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all connections
